image: hseeberger/scala-sbt:8u222_1.3.5_2.13.1

build:
    stage: build
    script: sbt clean compile

test:
    stage: test
    script: 
        - apt-get install -y gcc-arm-linux-gnueabi
        - apt-get install -y qemu
        - apt-get install -y qemu-user
        - sbt compile assembly
        - sbt test
